# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Notes
## If > is used, ignores new lines until next item.

# Site settings

## Options:
title: Insert Title Here
email: insert.email.here@site.com
description: >
  Enter
  Description
  Here
baseurl:
url: 
twitter_username: 
github_username: 
drupal_username:

# Build Settings
markdown: kramdown
theme: jekyll-theme-modernist

# SEO
twitter:
  username:

sass:
  sass_dir: some/directory

plugins:
  - jekyll-assets
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag
